---
- name: Create rados gateway directories
  ansible.builtin.file:
    path: "/var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ rgw_zone }}.{{ ansible_facts['hostname'] }}.{{ item.instance_name }}"
    state: directory
    owner: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    mode: "{{ ceph_directories_mode }}"
  loop: "{{ rgw_instances }}"

- name: Create rgw keyrings
  ceph_key:
    name: "client.rgw.{{ rgw_zone }}.{{ ansible_facts['hostname'] }}.{{ item.instance_name }}"
    cluster: "{{ cluster }}"
    user: "client.bootstrap-rgw"
    user_key: "/var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring"
    dest: "/var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ rgw_zone }}.{{ ansible_facts['hostname'] }}.{{ item.instance_name }}/keyring"
    caps:
      osd: 'allow rwx'
      mon: 'allow rw'
    import_key: false
    owner: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    mode: "{{ ceph_keyring_permissions }}"
  no_log: "{{ no_log_on_ceph_key_tasks }}"
  environment:
    CEPH_CONTAINER_IMAGE: "{{ ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment | bool else '' }}"
    CEPH_CONTAINER_BINARY: "{{ container_binary }}"
  with_items: "{{ rgw_instances }}"
  when: cephx | bool
