---
name: molecule

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: community
            scenario: molecule-all-in-one
            release: squid
            distro: debian-systemd:bookworm
          - repository: community
            scenario: molecule-all-in-one
            release: squid
            distro: ubuntu-systemd:jammy
          - repository: community
            scenario: molecule-all-in-one
            release: tentacle
            distro: centos-systemd:stream10
          - repository: community
            scenario: molecule-all-in-one
            release: tentacle
            distro: ubuntu-systemd:noble
          - repository: community
            scenario: molecule-all-in-one
            release: umbrella
            distro: centos-systemd:stream10
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: "tests/requirements.txt"

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox -c tox-molecule.ini -e ${{ matrix.scenario }}
        env:
          DOCKER_IMAGE_TAG: ${{ matrix.distro }}
          CEPH_REPOSITORY: ${{ matrix.repository }}
          CEPH_STABLE_RELEASE: ${{ matrix.release }}
